[package]
authors = ["Andy Caldwell <andrew.caldwell@metaswitch.com>"]
name = "pinboard"
description = "A lock-free, threadsafe way to publish data, just stick it on the pinboard"
license = "MIT"
repository = "https://github.com/bossmc/pinboard"
version = "0.10.0"
keywords = ["concurrency", "lock-free", "threading", "thread-safety"]
categories = ["concurrency"]

[badges]
travis-ci = { repository = "bossmc/pinboard" }

[dependencies]
crossbeam = "0.2.10"
